services:
  boundtwo-database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "bound2_password"
      POSTGRES_DB: "boundtwo"
    ports:
      - "54390:5432"
    container_name: boundtwo-postgres-database
    networks:
      - donda-network

  graduation-api:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/usr/app
    ports:
      - "3031:3031"
    restart: always
    container_name: graduation-node-api
    networks:
      - donda-network


networks:
  donda-network:
    driver: bridge

